"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useMe } from "@/lib/use-me";
import { api, fmtNum, PLATFORM_LABEL, FORMAT_LABEL } from "@/lib/api";
import { useAction, Spinner, Badge } from "@/components/ui";
type A = { totals: { posts: number; views: number; likes: number; comments: number; shares: number }; by_platform: Record<string, { posts: number; views: number; likes: number; comments: number; shares: number }>; by_format: Record<string, { posts: number; views: number }>; by_hour: Record<string, { posts: number; views: number }>; top_posts: { postId: string; contentId: string; hook: string | null; platform: string; views: number; likes: number; comments: number; outlier: boolean; permalink: string | null; thumbnail_url: string | null; publishedAt: string }[]; posts: { postId: string; contentId: string; hook: string | null; platform: string; format: string; views: number; likes: number; comments: number; shares: number; publishedAt: string; outlier: boolean }[]; insights: string[] };
type Attr = { sites: { id: string; domain: string; verifiedAt: string | null }[]; report: { source: string; event: string; count: number; value: number }[] };
/** Analytics (M15) + attribution summary (M16). */
export default function Analytics() {
  const { workspaceId } = useMe(); const { run, wall } = useAction(); const [days, setDays] = useState(30); const [a, setA] = useState<A | null>(null); const [attr, setAttr] = useState<Attr | null>(null);
  useEffect(() => { if (!workspaceId) return; const from = new Date(Date.now() - days * 86.4e6).toISOString(); api<A>(`/workspaces/${workspaceId}/analytics?from=${from}`).then(setA); api<Attr>(`/workspaces/${workspaceId}/tracking?from=${from}`).then(setAttr).catch(() => {}); }, [workspaceId, days]);
  const csv = () => { if (!a) return; const rows = [["post_id", "platform", "format", "hook", "published_at", "views", "likes", "comments", "shares"], ...a.posts.map((p) => [p.postId, p.platform, p.format, JSON.stringify(p.hook ?? ""), p.publishedAt, p.views, p.likes, p.comments, p.shares])]; const el = document.createElement("a"); el.href = URL.createObjectURL(new Blob([rows.map((r) => r.join(",")).join("\n")], { type: "text/csv" })); el.download = "analytics.csv"; el.click(); };
  if (!a) return <div className="py-20 grid place-items-center"><Spinner /></div>;
  const maxV = Math.max(1, ...Object.values(a.by_platform).map((p) => p.views));
  const bySource = (attr?.report ?? []).reduce<Record<string, Record<string, number>>>((m, r) => { (m[r.source] ??= {})[r.event] = r.count; return m; }, {});
  return (
    <div>{wall}
      <div className="flex flex-wrap items-center justify-between gap-2"><h1 className="text-2xl font-extrabold">Analytics</h1><div className="flex gap-2 items-center"><select className="input w-auto" value={days} onChange={(e) => setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><button className="btn-secondary" onClick={csv}>Export CSV</button></div></div>
      <div className="mt-4 grid grid-cols-2 md:grid-cols-5 gap-3">{[["Posts", a.totals.posts], ["Views", a.totals.views], ["Likes", a.totals.likes], ["Comments", a.totals.comments], ["Shares", a.totals.shares]].map(([l, v]) => <div key={l as string} className="kpi"><div className="text-xs text-[var(--color-muted)]">{l}</div><div className="text-2xl font-extrabold">{fmtNum(v as number)}</div></div>)}</div>
      {a.insights.length > 0 && <div className="mt-4 card p-4 bg-brand-50 border-brand-100"><div className="label">Insights</div><ul className="text-sm space-y-1">{a.insights.map((i) => <li key={i}>💡 {i}</li>)}</ul></div>}
      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div className="card p-4"><div className="label">Views by platform</div>{Object.entries(a.by_platform).length === 0 && <p className="text-sm text-[var(--color-muted)]">No published posts yet.</p>}{Object.entries(a.by_platform).map(([p, v]) => <div key={p} className="mt-2 text-sm"><div className="flex justify-between"><span>{PLATFORM_LABEL[p]} · {v.posts} posts</span><span>{fmtNum(v.views)}</span></div><div className="h-2 rounded bg-[var(--color-surface-2)]"><div className="h-2 rounded bg-brand-600" style={{ width: `${(100 * v.views) / maxV}%` }} /></div></div>)}</div>
        <div className="card p-4"><div className="label">Avg views by format</div>{Object.entries(a.by_format).sort((x, y) => y[1].views / y[1].posts - x[1].views / x[1].posts).map(([f, v]) => <div key={f} className="flex justify-between text-sm py-1 border-b border-[var(--color-hairline)]"><span>{FORMAT_LABEL[f]} ({v.posts})</span><b>{fmtNum(Math.round(v.views / v.posts))}</b></div>)}</div>
        <div className="card p-4"><div className="label">Best posting hours (UTC)</div><div className="flex items-end gap-1 h-24">{Array.from({ length: 24 }, (_, h) => { const v = a.by_hour[h]; const avg = v ? v.views / v.posts : 0; const mx = Math.max(1, ...Object.values(a.by_hour).map((x) => x.views / x.posts)); return <div key={h} title={`${h}:00 · ${fmtNum(Math.round(avg))} avg`} className="flex-1 bg-brand-600 rounded-t" style={{ height: `${(100 * avg) / mx}%`, opacity: v ? 1 : 0.15 }} />; })}</div></div>
        <div className="card p-4"><div className="label">Website attribution</div>{!attr?.sites.length ? <p className="text-sm text-[var(--color-muted)]">Install the tracking snippet to see visits, signups and purchases by platform. <Link className="underline" href="/app/settings/tracking">Set up</Link></p> : <table className="w-full text-sm"><thead><tr className="text-left text-[var(--color-muted)]"><th>Source</th><th>Visits</th><th>Signups</th><th>Purchases</th></tr></thead><tbody>{Object.entries(bySource).map(([s, e]) => <tr key={s} className="border-t border-[var(--color-hairline)]"><td className="py-1 capitalize">{s}</td><td>{e.pageview ?? 0}</td><td>{e.signup ?? 0}</td><td>{e.purchase ?? 0}</td></tr>)}</tbody></table>}</div>
      </div>
      <div className="mt-4 card overflow-hidden"><div className="p-3 label">Top posts</div><table className="w-full text-sm"><thead className="bg-[var(--color-surface-2)] text-left"><tr><th className="p-3">Post</th><th className="p-3">Platform</th><th className="p-3">Views</th><th className="p-3">Likes</th><th className="p-3">Comments</th><th className="p-3"></th></tr></thead><tbody>{a.top_posts.map((p) => <tr key={p.postId} className="border-t border-[var(--color-hairline)]"><td className="p-3 flex items-center gap-2">{p.thumbnail_url && /* eslint-disable-next-line @next/next/no-img-element */ <img src={p.thumbnail_url} alt={`Thumbnail for ${p.hook ?? "post"} on ${PLATFORM_LABEL[p.platform]}`} className="h-10 w-6 rounded object-cover" />}<Link href={`/app/content/${p.contentId}`} className="hover:underline">{p.hook}</Link>{p.outlier && <Badge tone="green">breakout</Badge>}</td><td className="p-3">{PLATFORM_LABEL[p.platform]}</td><td className="p-3">{fmtNum(p.views)}</td><td className="p-3">{fmtNum(p.likes)}</td><td className="p-3">{fmtNum(p.comments)}</td><td className="p-3"><button className="btn-secondary px-2 py-1 text-xs" onClick={() => run(() => api(`/content/${p.contentId}/similar`, { method: "POST", json: { count: 5 } }), "Generating similar")}>Generate similar</button></td></tr>)}{a.top_posts.length === 0 && <tr><td className="p-6 text-[var(--color-muted)]" colSpan={6}>Publish posts to see performance here.</td></tr>}</tbody></table></div>
    </div>
  );
}
