"use client";
import { useCallback, useEffect, useState } from "react";
import { useMe } from "@/lib/use-me";
import { api, PLATFORM_LABEL, FORMAT_LABEL } from "@/lib/api";
import { useAction, Spinner, Badge, statusTone, Modal, Empty } from "@/components/ui";
import { SchedulePicker } from "@/components/schedule-picker";
type Auto = { id: string; name: string; mode: string; approval: string; status: string; kind?: string; lastRunAt: string | null; nextRunAt: string | null; config: Record<string, unknown> & { social_account_ids: string[]; posts_per_day: number; horizon_days: number; times: string[]; weekdays: number[]; format_mix: Record<string, number>; source: string; min_spacing_minutes: number; max_per_platform_per_day: number; ugc_categories?: string[]; ugc_style_tags?: string[] } };
type Social = { id: string; platform: string; handle: string | null; status: string };
type Preview = { slots: number; per_account: Record<string, number>; will_generate: number; library_items_available: number; library_clips_available: number | null; saves_used: number; saves_limit: number | null; warnings: string[] };
const DEFAULT = { name: "Daily content", mode: "continuous", approval: "calendar", config: { social_account_ids: [] as string[], posts_per_day: 1, horizon_days: 14, times: ["09:00", "18:00"], weekdays: [1, 2, 3, 4, 5], format_mix: { ai_ugc: 0.4, slideshow: 0.3, hook_demo: 0.2, meme: 0.1 } as Record<string, number>, source: "mixed", min_spacing_minutes: 120, max_per_platform_per_day: 3, ugc_categories: [] as string[], ugc_style_tags: [] as string[] } };
/** Automations (M14): rule builder, preview, run now, run log. */
export default function Automations() {
  const { workspaceId, me } = useMe(); const { run, busy, wall } = useAction();
  const [autos, setAutos] = useState<Auto[] | null>(null); const [socials, setSocials] = useState<Social[]>([]); const [open, setOpen] = useState(false); const [f, setF] = useState(DEFAULT); const [preview, setPreview] = useState<Preview | null>(null); const [detail, setDetail] = useState<{ automation: Auto; runs: { id: string; startedAt: string; status: string; generated: number; scheduled: number; skipped: number; errors: string[] }[] } | null>(null);
  const load = useCallback(() => workspaceId && api<{ automations: Auto[] }>(`/workspaces/${workspaceId}/automations`).then((r) => setAutos(r.automations)), [workspaceId]);
  useEffect(() => { load(); if (workspaceId) api<{ socials: Social[] }>(`/workspaces/${workspaceId}/socials`).then((r) => setSocials(r.socials.filter((s) => s.status === "active"))); }, [load, workspaceId]);
  const create = async () => { const r = await run(() => api<{ automation: Auto }>(`/workspaces/${workspaceId}/automations`, { method: "POST", json: f }), "Automation created"); if (r) { const p = await api<Preview>(`/automations/${r.automation.id}/preview`, { method: "POST" }); setPreview(p); setOpen(false); load(); } };
  const patch = (a: Auto, body: Record<string, unknown>, msg: string) => run(async () => { await api(`/automations/${a.id}`, { method: "PATCH", json: body }); load(); }, msg);
  const runNow = (a: Auto) => run(async () => { await api(`/automations/${a.id}/run`, { method: "POST" }); load(); }, "Running — check Calendar in a minute");
  const showPreview = (a: Auto) => run(async () => setPreview(await api<Preview>(`/automations/${a.id}/preview`, { method: "POST" })));
  return (
    <div>{wall}
      <div className="flex items-center justify-between"><h1 className="text-2xl font-extrabold">Automations</h1><button className="btn-primary" onClick={() => setOpen(true)} disabled={!me?.plan.limits.scheduling}>+ New automation</button></div>
      {!me?.plan.limits.scheduling && <p className="mt-2 text-sm text-[var(--color-warning)]">Automations need a paid plan for scheduling.</p>}
      {!autos ? <div className="py-20 grid place-items-center"><Spinner /></div> : autos.length === 0 ? <div className="mt-6"><Empty title="No automations yet" body="Set a cadence and format mix; Velocity fills your calendar automatically." /></div> : (
        <div className="mt-4 grid gap-3">{autos.map((a) => <div key={a.id} className="card p-4 flex flex-wrap items-center gap-3">
          <div className="flex-1"><div className="flex items-center gap-2"><span className="font-semibold">{a.name}</span>{a.kind === "ghost_mode" && <Badge tone="brand">Ghost Mode</Badge>}<Badge tone={statusTone(a.status)}>{a.status}</Badge><Badge>{a.mode === "continuous" ? "continuous" : "one-shot"}</Badge><Badge>{a.approval === "auto" ? "auto-publish" : a.approval === "blitz" ? "approve in Velocity mode" : "approve in Calendar"}</Badge></div>
            <div className="text-xs text-[var(--color-muted)] mt-1">{a.config.posts_per_day}/day · {a.config.horizon_days} days · {a.config.times.join(", ")} · {a.config.social_account_ids.length} accounts · last run {a.lastRunAt ? new Date(a.lastRunAt).toLocaleString() : "never"}</div></div>
          <button className="btn-secondary" onClick={() => showPreview(a)}>Preview</button><button className="btn-secondary" onClick={() => api<typeof detail>(`/automations/${a.id}`).then(setDetail)}>Runs</button><button className="btn-primary" onClick={() => runNow(a)}>Run now</button>
          <button className="btn-ghost" onClick={() => patch(a, { status: a.status === "active" ? "paused" : "active" }, a.status === "active" ? "Paused" : "Resumed")}>{a.status === "active" ? "Pause" : "Resume"}</button><button className="btn-ghost text-[var(--color-danger)]" onClick={() => run(async () => { await api(`/automations/${a.id}`, { method: "DELETE" }); load(); }, "Deleted")}>Delete</button>
        </div>)}</div>
      )}
      <Modal open={open} onClose={() => setOpen(false)} title="New automation" wide><div className="grid gap-4 md:grid-cols-2 text-sm">
        <div><label className="label">Name</label><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></div>
        <div><label className="label">Mode</label><select className="input" value={f.mode} onChange={(e) => setF({ ...f, mode: e.target.value })}><option value="continuous">Continuous (keeps calendar full)</option><option value="one_shot">One-shot (fill once)</option></select></div>
        <div className="md:col-span-2"><label className="label">Accounts</label><div className="flex flex-wrap gap-2">{socials.map((s) => <button key={s.id} onClick={() => setF({ ...f, config: { ...f.config, social_account_ids: f.config.social_account_ids.includes(s.id) ? f.config.social_account_ids.filter((x) => x !== s.id) : [...f.config.social_account_ids, s.id] } })} className={`badge px-3 py-1.5 ${f.config.social_account_ids.includes(s.id) ? "bg-brand-600 text-white" : "bg-[var(--color-surface-2)]"}`}>{PLATFORM_LABEL[s.platform]} @{s.handle}</button>)}{socials.length === 0 && <span className="text-[var(--color-muted)]">Connect a social account first.</span>}</div></div>
        <div><label className="label">Posts per day (per account)</label><input type="number" min={1} max={10} className="input" value={f.config.posts_per_day} onChange={(e) => setF({ ...f, config: { ...f.config, posts_per_day: Number(e.target.value) } })} /></div>
        <div><label className="label">Horizon (days)</label><input type="number" min={1} max={60} className="input" value={f.config.horizon_days} onChange={(e) => setF({ ...f, config: { ...f.config, horizon_days: Number(e.target.value) } })} /></div>
        <SchedulePicker times={f.config.times} weekdays={f.config.weekdays} onTimesChange={(times) => setF({ ...f, config: { ...f.config, times } })} onWeekdaysChange={(weekdays) => setF({ ...f, config: { ...f.config, weekdays } })} />
        <div className="md:col-span-2"><label className="label">Format mix</label><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{Object.keys(FORMAT_LABEL).filter((k) => k !== "upload").map((k) => <label key={k} className="flex items-center gap-2"><span className="w-24">{FORMAT_LABEL[k]}</span><input type="range" min={0} max={1} step={0.1} value={f.config.format_mix[k] ?? 0} onChange={(e) => setF({ ...f, config: { ...f.config, format_mix: { ...f.config.format_mix, [k]: Number(e.target.value) } } })} /></label>)}</div></div>
        {(f.config.format_mix.human_ugc ?? 0) > 0 && <div className="md:col-span-2 rounded-xl bg-[var(--color-surface-2)] p-3 space-y-2"><label className="label">UGC library targeting (optional)</label><p className="text-xs text-[var(--color-muted)]">Restrict which videos from the clip library this automation draws from. Leave blank to use any available clip.</p>
          <div className="grid grid-cols-2 gap-2">
            <input className="input" placeholder="Categories, comma separated" value={f.config.ugc_categories.join(",")} onChange={(e) => setF({ ...f, config: { ...f.config, ugc_categories: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) } })} />
            <input className="input" placeholder="Style tags, comma separated" value={f.config.ugc_style_tags.join(",")} onChange={(e) => setF({ ...f, config: { ...f.config, ugc_style_tags: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) } })} />
          </div>
        </div>}
        <div><label className="label">Content source</label><select className="input" value={f.config.source} onChange={(e) => setF({ ...f, config: { ...f.config, source: e.target.value } })}><option value="mixed">Library first, then generate</option><option value="library">Library only</option><option value="generate">Generate new only</option></select></div>
        <div><label className="label">Approval</label><select className="input" value={f.approval} onChange={(e) => setF({ ...f, approval: e.target.value })}><option value="calendar">Approve in Calendar</option><option value="blitz">Approve in Velocity mode</option><option value="auto">Auto-publish</option></select></div>
        <div><label className="label">Min spacing (minutes)</label><input type="number" className="input" value={f.config.min_spacing_minutes} onChange={(e) => setF({ ...f, config: { ...f.config, min_spacing_minutes: Number(e.target.value) } })} /></div>
        <div><label className="label">Max per platform per day</label><input type="number" className="input" value={f.config.max_per_platform_per_day} onChange={(e) => setF({ ...f, config: { ...f.config, max_per_platform_per_day: Number(e.target.value) } })} /></div>
        <div className="md:col-span-2 flex justify-end gap-2"><button className="btn-ghost" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" disabled={busy || f.config.social_account_ids.length === 0} onClick={create}>Create & preview</button></div>
      </div></Modal>
      <Modal open={!!preview} onClose={() => setPreview(null)} title="Preview">{preview && <div className="text-sm space-y-2"><p><b>{preview.slots}</b> posts will be scheduled; <b>{preview.will_generate}</b> new pieces generated ({preview.library_items_available} available in library).</p>{preview.library_clips_available !== null && <p>{preview.library_clips_available} UGC clips match your library targeting filters.</p>}<p>Saves: {preview.saves_used}/{preview.saves_limit ?? "∞"}.</p>{preview.warnings.map((w) => <p key={w} className="text-[var(--color-warning)]">⚠ {w}</p>)}</div>}</Modal>
      <Modal open={!!detail} onClose={() => setDetail(null)} title="Run log">{detail && (detail.runs.length === 0 ? <p className="text-sm text-[var(--color-muted)]">No runs yet.</p> : <table className="w-full text-sm"><thead><tr className="text-left"><th>Started</th><th>Status</th><th>Gen</th><th>Sched</th><th>Skip</th></tr></thead><tbody>{detail.runs.map((r) => <tr key={r.id} className="border-t"><td className="py-1">{new Date(r.startedAt).toLocaleString()}</td><td><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td>{r.generated}</td><td>{r.scheduled}</td><td>{r.skipped}{r.errors.length > 0 && <span className="text-[var(--color-danger)]" title={r.errors.join("\n")}> ⚠</span>}</td></tr>)}</tbody></table>)}</Modal>
    </div>
  );
}
