"use client";
import { useEffect, useState } from "react";
import { useMe } from "@/lib/use-me";
import { api } from "@/lib/api";
import { useAction, Badge } from "@/components/ui";
type W = { id: string; url: string; events: string[]; enabled: boolean };
type K = { id: string; name: string | null; prefix: string; scopes: string[]; lastUsedAt: string | null; createdAt: string };
const SCOPES = ["content:read", "content:write", "publish", "analytics:read", "trends:read"];
export default function ApiKeys() {
  const { me } = useMe(); const { run, busy, wall } = useAction(); const [keys, setKeys] = useState<K[]>([]); const [rpm, setRpm] = useState(0); const [name, setName] = useState("Default"); const [scopes, setScopes] = useState<string[]>(SCOPES); const [created, setCreated] = useState<string | null>(null); const [hooks, setHooks] = useState<W[]>([]); const [evs, setEvs] = useState<string[]>([]); const [hookUrl, setHookUrl] = useState(""); const [hookEvents, setHookEvents] = useState<string[]>(["*"]); const [secret, setSecret] = useState<string | null>(null);
  const loadHooks = () => api<{ webhooks: W[]; events: string[] }>("/webhooks").then((r) => { setHooks(r.webhooks); setEvs(r.events); });
  const load = () => api<{ keys: K[]; rate_limit_rpm: number }>("/api-keys").then((r) => { setKeys(r.keys); setRpm(r.rate_limit_rpm); });
  useEffect(() => { load(); loadHooks(); }, []);
  const base = typeof window !== "undefined" ? window.location.origin : "";
  return (
    <div className="space-y-4 max-w-3xl">{wall}
      <div className="card p-5"><h2 className="font-bold">Create API key</h2>{!me?.plan.limits.apiRpm && <p className="text-sm text-[var(--color-warning)] mt-1">API access requires a paid plan.</p>}<div className="mt-3 flex flex-wrap gap-2 items-center"><input className="input w-48" value={name} onChange={(e) => setName(e.target.value)} />{SCOPES.map((s) => <label key={s} className="flex items-center gap-1 text-sm"><input type="checkbox" checked={scopes.includes(s)} onChange={() => setScopes(scopes.includes(s) ? scopes.filter((x) => x !== s) : [...scopes, s])} />{s}</label>)}<button className="btn-primary" disabled={busy || scopes.length === 0} onClick={() => run(async () => { const r = await api<{ key: string }>("/api-keys", { method: "POST", json: { name, scopes } }); setCreated(r.key); load(); })}>Create</button></div>
        {created && <div className="mt-3 rounded-xl bg-slate-900 text-slate-100 p-3 text-xs font-mono break-all">{created}<div className="mt-1 text-amber-300">Copy this now — it won't be shown again.</div></div>}</div>
      <div className="card overflow-hidden overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[var(--color-surface-2)] text-left"><tr><th className="p-3">Name</th><th className="p-3">Prefix</th><th className="p-3">Scopes</th><th className="p-3">Last used</th><th className="p-3"></th></tr></thead><tbody>{keys.map((k) => <tr key={k.id} className="border-t border-[var(--color-hairline)]"><td className="p-3">{k.name}</td><td className="p-3 font-mono">{k.prefix}…</td><td className="p-3">{k.scopes.map((s) => <Badge key={s}>{s}</Badge>)}</td><td className="p-3 text-[var(--color-muted)]">{k.lastUsedAt ? new Date(k.lastUsedAt).toLocaleString() : "never"}</td><td className="p-3 text-right"><button className="btn-ghost text-[var(--color-danger)] px-2 py-1 text-xs" onClick={() => run(async () => { await api(`/api-keys/${k.id}`, { method: "DELETE" }); load(); }, "Revoked")}>Revoke</button></td></tr>)}{keys.length === 0 && <tr><td className="p-6 text-[var(--color-muted)]" colSpan={5}>No keys yet. Rate limit on your plan: {rpm} requests/minute.</td></tr>}</tbody></table></div>
      <div className="card p-5 space-y-3"><h2 className="font-bold">Webhooks</h2><p className="text-sm text-[var(--color-muted)]">Receive signed POSTs when batches complete, content is saved, posts are scheduled, published or fail, and automations run.</p>
        <div className="flex flex-wrap gap-2 items-center"><input className="input w-72" placeholder="https://yourapp.com/hooks/velocity" value={hookUrl} onChange={(e) => setHookUrl(e.target.value)} />{["*", ...evs].map((e) => <label key={e} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={hookEvents.includes(e)} onChange={() => setHookEvents(hookEvents.includes(e) ? hookEvents.filter((x) => x !== e) : [...hookEvents, e])} />{e}</label>)}<button className="btn-primary" disabled={busy || !hookUrl} onClick={() => run(async () => { const r = await api<{ secret: string }>("/webhooks", { method: "POST", json: { url: hookUrl, events: hookEvents } }); setSecret(r.secret); setHookUrl(""); loadHooks(); })}>Add</button></div>
        {secret && <div className="rounded-xl bg-slate-900 text-slate-100 p-3 text-xs font-mono break-all">Signing secret: {secret}<div className="text-amber-300 mt-1">Shown once. Verify x-velocity-signature = t=…,v1=HMAC-SHA256(`${"${t}"}.${"${body}"}`).</div></div>}
        {hooks.map((h) => <div key={h.id} className="flex items-center gap-2 text-sm border-t border-[var(--color-hairline)] py-2"><code className="text-xs">{h.url}</code><span className="text-[var(--color-muted)]">{h.events.join(", ")}</span><button className="btn-ghost text-[var(--color-danger)] ml-auto px-2 py-1 text-xs" onClick={() => run(async () => { await api(`/webhooks?id=${h.id}`, { method: "DELETE" }); loadHooks(); }, "Removed")}>Remove</button></div>)}
      </div>
      <div className="card p-5 text-sm space-y-2"><h2 className="font-bold">Usage</h2><pre className="rounded-xl bg-slate-900 text-slate-100 p-3 text-xs overflow-x-auto">{`curl ${base}/api/v1/me -H "Authorization: Bearer sk_..."`}</pre><p>MCP endpoint for AI agents: <code className="bg-[var(--color-surface-2)] px-1">{base}/api/mcp</code> · OpenAPI: <a className="underline" href="/api/v1/openapi" target="_blank">/api/v1/openapi</a> · <a className="underline" href="/developers" target="_blank">Docs</a></p></div>
    </div>
  );
}
