"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useMe } from "@/lib/use-me";
import { api } from "@/lib/api";
import { useAction, Spinner } from "@/components/ui";
type Profile = { id: string; version: number; websiteUrl: string; data: Record<string, unknown> & { product_name: string; one_line_description: string; tagline: string; industry: string; key_features: string[]; differentiators: string[]; call_to_action: string; hooks_seed: string[]; content_pillars: string[]; language: string; tone_of_voice: { adjectives: string[]; do: string[]; dont: string[] }; target_audience: { segment: string; pain_points: string[]; desires: string[] }[]; brand: { primary_color?: string; secondary_color?: string } } };
const lines = (a: string[] | undefined) => (a ?? []).join("\n"); const toList = (s: string) => s.split("\n").map((x) => x.trim()).filter(Boolean);
export default function ProfileSettings() {
  const { workspaceId, workspace, me, refresh, setWorkspaceId } = useMe(); const { run, busy, wall } = useAction(); const sp = useSearchParams();
  const [p, setP] = useState<Profile | null | undefined>(undefined); const [f, setF] = useState<Record<string, string>>({}); const [wsName, setWsName] = useState(""); const [tz, setTz] = useState("UTC"); const [newName, setNewName] = useState("");
  useEffect(() => { if (!workspaceId) return; api<{ profile: Profile | null }>(`/workspaces/${workspaceId}/profile`).then((r) => { setP(r.profile); const d = r.profile?.data; setF({ product_name: d?.product_name ?? "", website_url: r.profile?.websiteUrl ?? "", tagline: d?.tagline ?? "", one_line_description: d?.one_line_description ?? "", industry: d?.industry ?? "", key_features: lines(d?.key_features), differentiators: lines(d?.differentiators), call_to_action: d?.call_to_action ?? "", hooks_seed: lines(d?.hooks_seed), content_pillars: lines(d?.content_pillars), language: d?.language ?? "en", adjectives: (d?.tone_of_voice?.adjectives ?? []).join(", "), audience: d?.target_audience?.[0]?.segment ?? "", pain_points: lines(d?.target_audience?.[0]?.pain_points), primary_color: d?.brand?.primary_color ?? "#1F3A93", secondary_color: d?.brand?.secondary_color ?? "#0B1F4B" }); }); setWsName(workspace?.name ?? ""); setTz(workspace?.timezone ?? "UTC"); }, [workspaceId, workspace]);
  const save = () => run(async () => { await api(`/workspaces/${workspaceId}/profile`, { method: "PUT", json: { data: { ...(p?.data ?? {}), product_name: f.product_name, website_url: f.website_url, tagline: f.tagline, one_line_description: f.one_line_description, industry: f.industry, key_features: toList(f.key_features), differentiators: toList(f.differentiators), call_to_action: f.call_to_action, hooks_seed: toList(f.hooks_seed), content_pillars: toList(f.content_pillars), language: f.language, tone_of_voice: { ...(p?.data?.tone_of_voice ?? { do: [], dont: [] }), adjectives: f.adjectives.split(",").map((x) => x.trim()).filter(Boolean) }, target_audience: [{ segment: f.audience, pain_points: toList(f.pain_points), desires: p?.data?.target_audience?.[0]?.desires ?? [] }], brand: { ...(p?.data?.brand ?? { screenshots: [] }), primary_color: f.primary_color, secondary_color: f.secondary_color }, category: p?.data?.category ?? "other", competitors: p?.data?.competitors ?? [], pricing_summary: p?.data?.pricing_summary ?? "", app_store_links: p?.data?.app_store_links ?? {}, confidence: {} } } }); refresh(); }, "Profile saved as a new version");
  const reanalyse = () => run(async () => { await api(`/workspaces/${workspaceId}/profile`, { method: "POST", json: { url: f.website_url } }); }, "Re-analysing — refresh in a minute");
  const saveWs = () => run(async () => { await api(`/workspaces/${workspaceId}`, { method: "PATCH", json: { name: wsName, timezone: tz } }); refresh(); }, "Workspace updated");
  const createWs = () => run(async () => { const r = await api<{ workspace: { id: string } }>("/workspaces", { method: "POST", json: { name: newName, timezone: tz } }); await refresh(); setWorkspaceId(r.workspace.id); setNewName(""); }, "Workspace created");
  if (p === undefined) return <div className="py-20 grid place-items-center"><Spinner /></div>;
  const F = (k: string, label: string, rows = 1) => <div><label className="label">{label}</label>{rows > 1 ? <textarea className="input" rows={rows} value={f[k] ?? ""} onChange={(e) => setF({ ...f, [k]: e.target.value })} /> : <input className="input" value={f[k] ?? ""} onChange={(e) => setF({ ...f, [k]: e.target.value })} />}</div>;
  return (
    <div className="grid gap-6 md:grid-cols-[1fr_320px]">{wall}
      <div className="card p-6 space-y-3">
        <div className="flex items-center justify-between"><h2 className="text-lg font-bold">Company profile {p ? <span className="text-xs text-[var(--color-faint)]">v{p.version}</span> : null}</h2><div className="flex gap-2"><button className="btn-secondary" onClick={reanalyse} disabled={!f.website_url}>Re-analyse site</button><button className="btn-primary" disabled={busy} onClick={save}>Save</button></div></div>
        <div className="grid md:grid-cols-2 gap-3">{F("product_name", "Product name")}{F("website_url", "Website URL")}{F("tagline", "Tagline")}{F("industry", "Industry")}{F("call_to_action", "Call to action")}{F("language", "Language (ISO)")}{F("adjectives", "Tone adjectives (comma separated)")}{F("audience", "Primary audience")}<div><label className="label">Primary colour</label><input type="color" className="input h-10" value={f.primary_color} onChange={(e) => setF({ ...f, primary_color: e.target.value })} /></div><div><label className="label">Secondary colour</label><input type="color" className="input h-10" value={f.secondary_color} onChange={(e) => setF({ ...f, secondary_color: e.target.value })} /></div></div>
        {F("one_line_description", "One-line description", 2)}{F("pain_points", "Audience pain points (one per line)", 3)}{F("key_features", "Key features (one per line)", 4)}{F("differentiators", "Differentiators (one per line)", 3)}{F("content_pillars", "Content pillars (one per line)", 3)}{F("hooks_seed", "Hook ideas (one per line)", 4)}
      </div>
      <div className="space-y-4">
        <div className="card p-5 space-y-3"><h2 className="font-bold">Workspace</h2><div><label className="label">Name</label><input className="input" value={wsName} onChange={(e) => setWsName(e.target.value)} /></div><div><label className="label">Timezone (IANA)</label><input className="input" value={tz} onChange={(e) => setTz(e.target.value)} placeholder="Europe/London" /></div><button className="btn-secondary" onClick={saveWs}>Update</button></div>
        <div className={`card p-5 space-y-3 ${sp.get("new") ? "ring-2 ring-brand-600" : ""}`}><h2 className="font-bold">New workspace</h2><p className="text-xs text-[var(--color-muted)]">{me?.workspaces.length}/{String(me?.plan.limits.workspaces)} used on {me?.plan.name}.</p><input className="input" placeholder="Brand name" value={newName} onChange={(e) => setNewName(e.target.value)} /><button className="btn-primary" disabled={!newName} onClick={createWs}>Create</button></div>
        <div className="card p-5 space-y-2 text-sm"><h2 className="font-bold">Account</h2><p className="text-[var(--color-muted)]">{me?.user?.email}</p><a className="btn-secondary" href="/api/auth/signout">Sign out</a><button className="btn-ghost text-[var(--color-danger)]" onClick={() => confirm("Delete your account? Data is purged after 30 days.") && run(async () => { await api("/me", { method: "DELETE" }); window.location.href = "/api/auth/signout"; })}>Delete account</button></div>
      </div>
    </div>
  );
}
