import { readFileSync, writeFileSync } from "fs";
const results = JSON.parse(readFileSync("out/results.json", "utf8"));
const groups = { "Marketing site": ["landing","pricing","faq","blog","blog-post","tool","compare","industry","developers","affiliates","contact","privacy","terms","notfound","login"], "Product": ["app-onboarding","app-velocity","app-content","app-content-detail","app-studio","app-calendar","app-automations","app-analytics","app-trends","app-characters","app-affiliate"], "Admin panel": ["app-admin","app-admin-accounts","app-admin-keys","app-admin-integrations"], "Settings": ["settings-profile","settings-socials","settings-billing","settings-members","settings-api","settings-tracking"] };
const titles = { faq: "FAQ", contact: "Contact — map & directions", privacy: "Privacy policy", terms: "Terms of service", notfound: "Custom 404 page", "app-admin-accounts": "Admin · Accounts", "app-admin-keys": "Admin · Keys & webhooks", "app-admin-integrations": "Admin · Integrations", landing: "Landing", pricing: "Pricing", blog: "Blog", "blog-post": "Blog post", tool: "SEO: Tool page", compare: "SEO: Comparison", industry: "SEO: Industry", developers: "API & MCP docs", affiliates: "Affiliate program", login: "Login (redirects to app when signed in)", "app-onboarding": "Onboarding", "app-velocity": "Velocity mode (swipe approval)", "app-content": "Content library", "app-content-detail": "Content detail", "app-studio": "Studio", "app-calendar": "Calendar", "app-automations": "Automations", "app-analytics": "Analytics", "app-trends": "Trends", "app-characters": "Characters", "app-affiliate": "Affiliate dashboard", "app-admin": "Admin", "settings-profile": "Settings · Profile & workspace", "settings-socials": "Settings · Social accounts", "settings-billing": "Settings · Billing", "settings-members": "Settings · Team", "settings-api": "Settings · API keys & webhooks", "settings-tracking": "Settings · Website tracking" };
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;");
const img = (n) => `data:image/png;base64,${readFileSync(`out/${n}.png`).toString("base64")}`;
const clean = (r) => (r.errors ?? []).filter((e) => !String(e).includes("404 (Not Found)")); // the 404 page legitimately returns 404
const total = results.length, errs = results.filter((r) => clean(r).length || r.error).length;
const cards = Object.entries(groups).map(([g, names]) => `<h2 id="${esc(g)}">${esc(g)}</h2><div class="grid">${names.map((n) => { const r = results.find((x) => x.name === n) ?? {}; const bad = r.error || (r.errors ?? []).filter((e) => !String(e).includes("404 (Not Found)")).length; return `<figure id="${n}" class="${bad ? "bad" : ""}"><a href="#v-${n}"><img loading="lazy" src="${img(n)}" alt="${esc(titles[n])}"></a><figcaption><b>${esc(titles[n])}</b><code>${esc(r.path ?? "")}</code><span class="${bad ? "err" : "ok"}">${bad ? "⚠ " + esc(r.error ?? clean(r).join("; ")) : "✓ rendered, no console errors"}</span>${r.h1 ? `<small>h1: ${esc(r.h1)}</small>` : ""}</figcaption></figure>`; }).join("")}</div>`).join("");
const full = results.map((r) => `<div class="view" id="v-${r.name}"><div class="bar"><b>${esc(titles[r.name])}</b> <code>${esc(r.path)}</code><a href="#top">✕ close</a></div><img src="${img(r.name)}" alt=""></div>`).join("");
writeFileSync("/mnt/user-data/outputs/Velocity_Page_Viewer.html", `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Velocity — page viewer (headless Chromium screenshots)</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>:root{--b:#1F3A93;--d:#0B1F4B}*{box-sizing:border-box}body{margin:0;font:14px/1.45 system-ui,sans-serif;background:#f6f8fb;color:#0f172a}header{background:var(--d);color:#fff;padding:16px 24px;display:flex;gap:14px;align-items:center;flex-wrap:wrap;position:sticky;top:0;z-index:5}header h1{margin:0;font-size:18px}.pill{background:#ffffff22;border-radius:999px;padding:4px 12px;font-size:13px}header nav a{color:#fff;opacity:.85;margin-left:12px;text-decoration:none}
main{padding:20px 24px}h2{margin:22px 0 10px;font-size:16px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(400px,1fr));gap:16px}figure{margin:0;background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden}figure.bad{border-color:#d93025}figure img{width:100%;display:block;aspect-ratio:16/10;object-fit:cover;object-position:top;border-bottom:1px solid #e2e8f0;cursor:zoom-in}figcaption{padding:10px 12px;display:grid;gap:3px}figcaption code{color:var(--b);font-size:12px}.ok{color:#0f9d58;font-size:12px}.err{color:#d93025;font-size:12px}figcaption small{color:#64748b}
.view{display:none;position:fixed;inset:0;background:#0f172a;z-index:10;overflow:auto}.view:target{display:block}.view .bar{position:sticky;top:0;background:var(--d);color:#fff;padding:10px 16px;display:flex;gap:12px;align-items:center}.view .bar a{margin-left:auto;color:#fff;text-decoration:none}.view .bar code{color:#cbd5e1}.view img{display:block;margin:0 auto;max-width:1280px;width:100%}
.note{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:14px 16px;margin-bottom:8px}</style></head>
<body id="top"><header><h1>Velocity · page viewer</h1><span class="pill">${total} pages rendered in headless Chromium</span><span class="pill">${errs ? errs + " with errors" : "0 console/page errors"}</span><span class="pill">1280×800, signed-in session, mock providers</span><nav>${Object.keys(groups).map((g) => `<a href="#${esc(g)}">${esc(g)}</a>`).join("")}</nav></header>
<main><div class="note">Each screenshot is a real render of the running application (Next.js production build) after client-side hydration, taken by a headless Chromium with an authenticated admin session on the Growth plan. Click any screenshot to view it full size. Data shown is from the mock-provider test run (synthetic characters, sandbox “publishing”, generated content).</div>${cards}</main>${full}</body></html>`);
console.log("viewer written", total, "pages,", errs, "with errors");
